export const characterList = [
"All-Loving Hero",
"The Antagonist",
"Anthropomorphic Personification",
"Anti-Hero",
"The Archmage",
"Audience Surrogate",
"Barefoot Sage",
"Big Fun",
"Blind Seer",
"Blue-Collar Warlock",
"Bruiser with a Soft Center",
"The Champion",
"The Chosen One",
"The Chooser of The One",
"Classical Hunter",
"Classic Villain",
"Commander Contrarian",
"The Conscience",
"The Corrupter",
"The Cynic",
"The Dragonslayer",
"The Drunken Sailor",
"Dumb Muscle",
"Eccentric Mentor",
"Enigmatic Empowering Entity",
"Evil Overlord",
"The Fair Folk",
"False Prophet",
"Father Neptune",
"The Ferryman",
"The Fool",
"Fool for Love",
"Genki Girl",
"Gentle Giant",
"The Good King",
"Granny Classic",
"The Grotesque",
"Herald",
"The Hero",
"Heroic Wannabe",
"The High Queen",
"Higher Self",
"Hunter of Monsters",
"Ideal Hero",
"The Idealist",
"Ineffectual Loner",
"Jeanne d'Archétype",
"Keet",
"The Kirk",
"The Klutz",
"Knight in Shining Armor",
"Lady and Knight",
"Loser Archetype",
"Lovable Rogue",
"Madonna Archetype",
"Magical Barefooter",
"The McCoy",
"Mentor Archetype",
"Messianic Archetype",
"Mock Millionaire",
"Modern Major General",
"Moses Archetype",
"My Girl Back Home",
"Obstructive Bureaucrat",
"Oedipus Complex",
"Old Soldier",
"The Paladin",
"The Paragon",
"The Patriarch",
"Person of Mass Destruction",
"The Pollyanna",
"Powers That Be",
"Prince Charming",
"Princess Classic",
"The Protagonist",
"A Protagonist Shall Lead Them (a.k.a. Leader Archetype)",
"Rebel Leader",
"Rebellious Spirit",
"Reluctant Monster",
"Satanic Archetype",
"Seeker Archetype",
"Shadow Archetype",
"Sidekick",
"The Sociopath",
"The Spock",
"Star-Crossed Lovers",
"The Storyteller",
"Threshold Guardians",
"Turn Coat",
"The Trickster",
"Wicked Stepmother",
"Wicked Witch",
"Witch Classic",
"Wizard Classic",
"Wolf Man",
"World's Best Warrior",
"World's Most Beautiful Woman",
"World's Strongest Man",
]