export const genreList = [
    "Mystery",
    "Science Fiction",
    "Fantasy",
    "Western",
    "Romance",
    "Espionage",
    "Pot-boiler",
    "Drama",
    "Alternate History",
    "Contemporary Fantasy",
    "Dark Fantasy",
    "Fairy Tale",
    "Fantasy of Manners",
    "Heroic Fantasy",
    "High Fantasy",
    "Historical Fantasy",
    "Low Fantasy",
    "Magical Realism",
    "Mythic Fantasy",
    "Superhero",
    "Sword and Sorcery",
    "Urban Fantasy",
    "Comedy Horror",
    "Creepy Kids Horror",
    "Gothic Horror",
    "Hauntings",
    "Historical Horror",
    "Lovecraftian",
    "Man-made Horror",
    "Monsters",
    "Mythic Horror",
    "Occult Horror",
    "Psychological Horror",
    "Quiet Horror",
    "Amateur Sleuth",
    "Bumbling Detective",
    "Caper",
    "Cozy Mystery",
    "Hardboiled",
    "Historical Mystery",
    "Howdunit",
    "Locked Room Mystery",
    "Multicultural and Diverse Mystery",
    "Paranormal Mystery",
    "Police Procedural",
    "Private Detective",
    "Whodunit",
    "Aliens",
    "Alternate History",
    "Alternate/Parallel Universe",
    "Apocalyptic/Post-Apocalyptic",
    "Biopunk",
    "Colonization Science Fiction",
    "Comedy Science Fiction",
    "Cyberpunk",
    "Dying Earth",
    "Dystopia",
    "Galactic Empire",
    "Generation Ship Science Fiction",
    "Immortality",
    "Lost Worlds",
    "Military Science Fiction",
    "Mind Transfer",
    "Mundane Science Fiction",
    "Mythic Science Fiction",
    "Nanopunk",
    "Robots/A.I.",
    "Science Fantasy",
    "Science Horror",
    "Slipstream Science Fiction",
    "Soft Science Fiction",
    "Space Exploration",
    "Space Opera",
    "SpyFi",
    "Steampunk",
    "Time Travel",
    "Utopia",
    "Action Thriller",
    "Comedy Thriller",
    "Conspiracy",
    "Crime Thriller",
    "Disaster Thriller",
    "Espionage Thriller",
    "Forensic Thriller",
    "Historical Thriller/Suspense",
    "Legal Thriller/Suspense",
    "Medical Thriller/Suspense",
    "Military Thriller/Suspense",
    "Mystery Thriller",
    "Paranormal Thriller/Suspense",
    "Political Thriller/Suspense",
    "Psychological Thriller/Suspense",
    "Religious Thriller/Suspense",
    "Technothriller",
    "Bounty Hunters Western",
    "Cattle Drive",
    "Comedy Western",
    "Gold Rush",
    "Gunfighters",
    "Land Rush Western",
    "Lawmen",
    "Mountain Men Western",
    "Outlaws Western",
    "Prairie Settlement Western",
    "Revenge Western",
    "Wagon Train",
    "Revenge",

]

